name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json
      -
        name: Install NPM packages
        run: npm ci
      -
        name: Test
        run: npm run test
      -
        name: Build
        run: npm run build
      -
        name: Check changes
        id: check-changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          changes="$(git status --porcelain ./docs)"
          if [ $? -ne 0 ]; then
            printf '%s\n' "$changes"
            exit 1
          fi
          if [ -z "$changes" ]; then
            echo 'No changes detected'
          else
            printf 'Changes detected:\n%s\n' "$changes"
            echo 'commit=yes' >>$GITHUB_OUTPUT
          fi
      -
        name: Commit
        if: steps.check-changes.outputs.commit == 'yes'
        run: |
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add docs
            git commit -m 'Rebuild app'
            git push




